apiVersion: batch/v1
kind: Job
metadata:
  name: guidellm-benchmark
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
      - name: guidellm
        image: ghcr.io/vllm-project/guidellm:latest
        env:
          - name: GUIDELLM_TARGET
            value: "URL_PLACEHOLDER"
          - name: GUIDELLM_PROFILE
            value: sweep
          - name: GUIDELLM_MAX_SECONDS
            value: "30"
          - name: GUIDELLM_DATA
            value: "prompt_tokens=256,output_tokens=128"
          - name: GUIDELLM_PROCESSOR
            value: "Qwen/Qwen3-0.6B"
          - name: HF_HOME
            value: /tmp/hf-cache
          - name: TRANSFORMERS_CACHE
            value: /tmp/hf-cache
          - name: XDG_CACHE_HOME
            value: /tmp
        volumeMounts:
          - name: cache
            mountPath: /tmp/hf-cache
          - name: results
            mountPath: /results
      volumes:
        - name: cache
          emptyDir: {}
        - name: results
          emptyDir: {}
