apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - quay-image-pull-secret.yaml
  - service-account.yaml
  - llm-infra.yaml

configMapGenerator:
  - name: qwen3-chat-template
    files:
      - qwen3_nonthinking.jinja=qwen3_nonthinking.jinja
    namespace: llmd-xeon

generatorOptions:
  disableNameSuffixHash: true
