apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen-vllm
  namespace: vllm-xeon
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    serviceAccountName: vllm-xeon-sa
    automountServiceAccountToken: false
    maxReplicas: 4
    minReplicas: 4
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources: {}
      runtime: vllm-runtime
      storageUri: 'hf://Qwen/Qwen3-0.6B'
