apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vllm-xeon

resources:
  - serving-runtime.yaml
  - inference-service.yaml
  - pod-monitor.yaml
  - service.yaml
  - quay-image-pull-secret.yaml
  - service-account.yaml

configMapGenerator:
  - name: qwen3-chat-template
    files:
      - qwen3_nonthinking.jinja=qwen3_nonthinking.jinja
    namespace: vllm-xeon

generatorOptions:
  disableNameSuffixHash: true
